Add swipe refresh element
avito-tech/android-ui-testing pull request #9
Opened 2018-05-04 23:56 UTC by bagza

2018-05-04 23:58 UTC, bagza commented on test-app/src/androidTest/java/com/avito/android/ui/test/SwipeRefreshTest.kt
> -    fun recyclerView_refresh_onPullToRefresh() {
This one was lying, there is no recyclerView on layout

2018-05-05 00:02 UTC, bagza commented on test-app/src/androidTest/java/com/avito/android/ui/test/SwipeRefreshTest.kt
>          Screen.swipeRefresh.list.actions.pullToRefresh()
To be honest, I don't think ListElement is a right place for pullToRefresh action. I do not touch it in order not to cause conflicts

2018-05-07 12:32 UTC, dsvoronin commented
Push something to re-trigger checks please

2018-05-07 17:21 UTC, dsvoronin requested changes
Need to update README

2018-05-10 12:46 UTC, dsvoronin requested changes

2018-05-10 12:46 UTC, dsvoronin commented on README.md
> +## Features
it's better to have `Features` block under configuration, because it tends to be huge

2018-05-10 12:46 UTC, dsvoronin commented on README.md
> +We should announce what the DoD is.
Let's say:
1. we have full test coverage of current features
2. we have docs about all features

that's 1.0, than we rethink some of weak points and address them in 2.0

2018-05-10 12:46 UTC, dsvoronin commented on README.md
> +swipeRefreshElement.checks.isRefreshing()
We need two things here: 
1. element instantiation
2. what element offers: checks, actions as call examples

2018-05-10 13:14 UTC, bagza commented on README.md
> +We should announce what the DoD is.
Need to make a checklist. Will put an issue on you.

2018-05-10 18:36 UTC, bagza commented
@dsvoronin let's merge it, leaving Readme work after #11

2018-05-10 20:35 UTC, dsvoronin approved these changes

2018-05-10 20:36 UTC, merged